title: Isaac Castillo Blog. Also View some of my work :)
email: icemancast@gmail.com
description: > # I have been doing design and web application development work for over
  15 years. I enjoy solving hard problems with code and have worked with various
  frameworks/libraries and languages; Kohana framework, PHP, MySQL, CSS, Sass,
  Capistrano, Git, Jquery, Emberjs and Wordpress just to name a few. My current
  framework development is Laravel, Reactjs and Wordpress. I am also in the process
  of releasing my first iOS application for a client written solely in React Native.
source: . # Where is source code
destination: ./_site # Where to compile
plugins_dir: ./_plugins
layouts_dir: ./_layouts
paginate: 3
permalink: pretty
future: false

# Site settings
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://icemancast.com" # the base hostname & protocol for your site
twitter_username: icemancast
github_username:  icemancast

# Build settings
markdown: kramdown

# Site map settings
sitemap:
  file: "/sitemap.xml"
  include_posts:
  - "/index.html"

# Supported gems
gems: [jekyll-paginate]
